config/routes.rb
Flutter::Application.routes.draw do
  resources :statuses
  resource :user, except: [:show]
  resource :session, :only => [:new, :create, :destroy]

  get ":screen_name" => 'users#show', as: :profile

  post ":screen_name/relationships" => "relationships#create", as: "follow"
  

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower_user, :class_name => "User", :foreign_key => "follower_id"
  belongs_to :followed_user, :class_name => "User", :foreign_key => "followed_id"

  validates :follower_id, uniqueness: { scope: [:followed_id] }
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  has_many :user_mentions
  
  validates :text, :length => { :maximum => 140, :minimum => 2 }
  default_scope { order("created_at DESC") }

  before_save :check_for_reply
  after_save :check_mentions
  
  def reply_user
    return nil unless reply_to
    @user = User.find(reply_to)
  end

  def mentioned_users
    return unless user_mentions = self.user_mentions
    users = []
    user_mentions.each do |mention|
      users << User.find(mention.user_id).screen_name
    end  
    return users
  end
  
private

  def check_for_reply
    username = text.scan(/\A@(\S+)/)
    return if username.empty?
    return unless user = User.find_by(screen_name: username[0])
    self.reply_to = user.id
  end
  
  def check_mentions  
    users = text.scan(/@(\w+)/).uniq
    return if users.empty?
    users.each do |user|
      if mentioned = User.find_by(screen_name: user)
        UserMention.create(status_id: self.id, user_id: mentioned.id)
      end
    end
  end
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :statuses
  has_many :follower_relationships, class_name: "Relationship", :foreign_key => "follower_id"
  has_many :followed_relationships, class_name: "Relationship", :foreign_key => "followed_id"
  has_many :followed_users, through: :follower_relationships
  has_many :follower_users, through: :followed_relationships
  
  EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  validates :email, :format => EMAIL_REGEX, :uniqueness => true
  validates :screen_name, :uniqueness => true, :length => 1..15, :format => /\A\w+\z/
  validates :full_name, :length => { :minimum => 2 }
  validates :password, :length => { :minimum => 8 }, 
    :format => { :with => /\d/, :message => "must have at least one number" }, 
    :exclusion => ["12345678"], 
    :if => :password_validatible?

  attr_accessor :password

  before_save :encrypt_password
  
  has_many :user_mentions

  def self.authenticate(email, password)
    return false unless user = self.find_by(:email => email)
    hashed_password = BCrypt::Engine.hash_secret(password, user.password_salt)
    return false unless hashed_password == user.password_hash
    user
  end

  def follow(user)
    follower_relationships.create(followed_id: user.id)
  end

  def following?(user)
    follower_relationships.find_by(followed_id: user.id).present?
  end

  def follower_user_count
    @follower_user_count ||= follower_users.count
  end

  def followed_user_count
    @followed_user_count ||= followed_users.count
  end

  def to_param
    screen_name  
  end

  def follower_ratio
    return nil if followed_user_count == 0
    follower_user_count.to_f / followed_user_count
  end

private

  def password_validatible?
    password.present? || new_record?
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/user_mention.rb
class UserMention < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :logout, :make_links

  def login_as(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(:id => session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def logout
    session.delete(:user_id)
  end

  def authenticate_user!
    redirect_to new_session_url unless logged_in?
  end

  def not_found!
    raise ActionController::RoutingError.new("Not Found")
  end
  
  def make_links(status, users)
    users.each do |user|
      status.gsub!("@#{user}", "<a href=\"/#{user}\">@#{user}</a>")
    end
    return status
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!, :set_followed_user

  def create
    current_user.follow(@followed_user)    
    redirect_to profile_url(@followed_user)
  end

private

  def set_followed_user
    @followed_user = User.find_by(screen_name: params[:screen_name]) || not_found!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, except: [:destroy]

  def create
    if user = User.authenticate(params[:email], params[:password])
      login_as(user)
      redirect_to statuses_url
    else
      flash.now[:alert] = "Invalid email or password!"
      render "new"
    end
  end

  def destroy
    if logged_in?
      logout
      redirect_to statuses_url
    else  
      redirect_to new_session_url
    end
  end

private

  def redirect_if_logged_in
    redirect_to statuses_url if logged_in?
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]

  def index
    @statuses = Status.all
  end

  def new
    @status = Status.new
  end

  def create
    @status = current_user.statuses.new(status_params)
    if @status.save
      redirect_to statuses_url, notice: "Status updated"
    else
      render "new"
    end
  end

private

  def status_params
    params.require(:status).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = User.find_by(screen_name: params[:screen_name]) || not_found!
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_as(@user)
      redirect_to statuses_url, :notice => "Welcome!"
    else
      render "new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to edit_user_url, notice: "Attributes updated succesfully"
    else
      render "edit"
    end
  end

private

  def user_params
    params.require(:user).permit(:screen_name, :full_name, :url, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flutter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="main-navigation">
    <div class="container">
      <ul class="left">
        <li><%= link_to "Flutter", "/", :class => "logo" %></li>
        <li><%= link_to "Statuses", statuses_path %></li>
        <% if logged_in? %>
          <li><%= link_to "New Status", new_status_path %></li>
        <% end %>
      </ul>

      <ul class="right">
        <% if logged_in? %>
          <li>Welcome, <%= link_to current_user.full_name, profile_path(current_user.screen_name) %></li>
          <li><%= link_to "Settings", edit_user_path %></li>
          <li><%= link_to "Logout", session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <div class="content-wrapper">
      <% if flash[:notice] %>
        <div class="flash notice"><%= flash[:notice] %></div>
      <% end %>

      <% if flash[:alert] %>
        <div class="flash alert"><%= flash[:alert] %></div>
      <% end %>

      <div class="main-content">
        <%= yield %>
      </div>

      <aside class="sidebar">
        <%= yield(:sidebar) %>
      </aside>
    </div>
  </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if record.errors.any? %>
  <div class="validation-errors">
    <p>The following errors occurred:</p>
    <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/statuses/_list.html.erb
<div class="content-box">
  <h2>Statuses</h2>
  <ol class="statuses">
    <% statuses.each do |status| %>
      <li>
        <%= gravatar_image_tag(status.user.email, alt: status.user.full_name, class: "avatar") %>
        <div class="status">
          <%= link_to profile_path(status.user.screen_name), class: 'user' do %>
            <span class="full-name"><%= status.user.full_name %></span>
            <span class="screen-name">@<%= status.user.screen_name %></span>
          <% end %>
          <time><%= time_ago_in_words(status.created_at) %> ago</time>
          <p class="status-text"><%= make_links(status.text, status.mentioned_users).html_safe %></p>
          <% if status.reply_user %>
            <em>In reply to <%= link_to  "@#{status.reply_user.screen_name}", profile_path(status.reply_user.screen_name) %></em>
          <% end %>
        </div>
      </li>
    <% end %>
  </ol>
</div>

app/views/statuses/index.html.erb
<%= render "list", statuses: @statuses %>

app/views/statuses/new.html.erb
<div class="content-box">
  <h2>New Status</h2>

  <div class="inner">
    <%= render "shared/errors", record: @status %>
    <%= form_for @status do |f| %>
      <div class="field">
        <%= f.label :text, "New Status" %>
        <%= f.text_area :text %>
      </div>
      
      <%= f.submit "Submit", :class => "button" %>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(user, url: user_path) do |f| %>
  <div class="field">
    <%= f.label :screen_name, "Screen Name" %>
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :full_name, "Full Name" %>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :url, "URL" %>
    <%= f.url_field :url %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  
  <%= f.submit button_text, :class => "button" %>
<% end %>

app/views/users/edit.html.erb
<div class="content-box">
  <h2>Edit Settings</h2>

  <div class="inner">
    <%= render "shared/errors", record: @user %>
    <%= render "form", user: @user, button_text: "Save Settings" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="content-box">
  <h2>Sign Up</h2>

  <div class="inner">
    <%= render "shared/errors", record: @user %>
    <%= render "form", user: @user, button_text: "Sign Up" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-header content-box">
  <div class="user-info">
    <%= gravatar_image_tag(@user.email, alt: @user.full_name, class: "avatar") %>
    <h1 class="full-name"><%= @user.full_name %></h2>
    <h2 class="screen-name">@<%= @user.screen_name %></h3>
  </div>

  <ul class="stats">
    <li>
      <a href="#">
        <strong><%= @user.statuses.count %></strong> Statuses
      </a>
    </li>

    <li>
      <a href="#">
        <strong><%= @user.followed_users.count %></strong> Following
      </a>
    </li>

    <li>
      <a href="#">
        <strong><%= @user.follower_users.count %></strong> Followers
      </a>
    </li>
    <li>
      <a href="#">
        <% if @user.follower_ratio != nil %>
          <strong><%= @user.follower_ratio %></strong> Follower Ratio
        <% else %>
          <strong>No Follower Ratio</strong>
        <% end %>
      </a>
    </li>
  </ul>

  <% if !logged_in? %>
    <%= link_to "Sign in to follow", new_session_path, class: "follow-button button" %>
  <% elsif current_user != @user %>
    <% if current_user.following?(@user) %>
      <a href="#" class="follow-button button">Unfollow</a>
    <% else %>
      <%= link_to "Follow", follow_url(screen_name: @user.screen_name), method: :post, class: "follow-button button" %>
    <% end %>
  <% end %>
</div>

<%= render "statuses/list", statuses: @user.statuses %>